// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJU6AqS-VBmI2r_I7hNLcELANmFMnQUZ4',
    appId: '1:931982465423:web:c212d7cde9173a4a0393fa',
    messagingSenderId: '931982465423',
    projectId: 'quiz-e531e',
    authDomain: 'quiz-e531e.firebaseapp.com',
    storageBucket: 'quiz-e531e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDagHTKtrEW-VSGSfsbBkgfWANaoYqRK6E',
    appId: '1:931982465423:android:7f994e5b13b408ac0393fa',
    messagingSenderId: '931982465423',
    projectId: 'quiz-e531e',
    storageBucket: 'quiz-e531e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2T6RmK90wnxyo7OvZL2-YmshGngsqAeU',
    appId: '1:931982465423:ios:17f1c83a50f4ff470393fa',
    messagingSenderId: '931982465423',
    projectId: 'quiz-e531e',
    storageBucket: 'quiz-e531e.appspot.com',
    iosClientId: '931982465423-q5plmf9gmgr6ib1hjqrcl4f1lkspbbsd.apps.googleusercontent.com',
    iosBundleId: 'ru.alllll.quiz.quizTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2T6RmK90wnxyo7OvZL2-YmshGngsqAeU',
    appId: '1:931982465423:ios:17f1c83a50f4ff470393fa',
    messagingSenderId: '931982465423',
    projectId: 'quiz-e531e',
    storageBucket: 'quiz-e531e.appspot.com',
    iosClientId: '931982465423-q5plmf9gmgr6ib1hjqrcl4f1lkspbbsd.apps.googleusercontent.com',
    iosBundleId: 'ru.alllll.quiz.quizTest',
  );
}
